### PR TITLE
Copy mods from server to players

### PR DESCRIPTION
**Pull request by ZambrOvosky**
#94

### CODE REVIEW

**Comment by Foxlider** [comment]
Pull request should not be made directly to master 
(but this is my fault, I haven't set up the collaboration guidelines)

**Comment by ZambrOvosky** [comment]
Srry, nevermind

**Comment by Foxlider** [comment]
Don't worry though, this code shouldn't be necessary for the next version of the profile view

**Comment by Foxlider** [comment]
Although the code is valid, given the big changes to the profile view, I have to close this PR.

**Pull request closed without merging**
